version: '3.8'

services:
  daitem-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 00000000
      MYSQL_DATABASE: daitem_user
    ports:
      - "3306:3306"
    volumes:
      - daitem-db-data:/var/lib/mysql
    restart: always

  daitem-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - daitem-redis-data:/data
    restart: always

  daitem-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://daitem-db:3306/daitem_user?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 00000000
      SPRING_REDIS_HOST: daitem-redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - daitem-db
      - daitem-redis
    restart: always

volumes:
  daitem-db-data:
  daitem-redis-data:
